/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuyCryptoRequest {
  'paymentMethod' : string,
  'asset' : string,
  'fiatAmount' : number,
  'fiatCurrency' : string,
}
export interface ExchangeRate {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface PortfolioValue { 'totalCDF' : number, 'totalUSD' : number }
export interface SellCryptoRequest {
  'asset' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface SetExchangeRateRequest {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface StakeRecord {
  'id' : bigint,
  'durationDays' : bigint,
  'startTime' : bigint,
  'userId' : Principal,
  'claimed' : boolean,
  'rewardRate' : number,
  'amount' : number,
}
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'asset' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'fiatAmount' : number,
  'txType' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface TransactionResult {
  'newBalance' : [] | [WalletBalance],
  'message' : string,
  'success' : boolean,
}
export interface UpdateProfileRequest {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export interface UserProfile {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletBalance {
  'btc' : number,
  'cdf' : number,
  'eth' : number,
  'okp' : number,
  'usd' : number,
  'usdt' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyCrypto' : ActorMethod<[BuyCryptoRequest], TransactionResult>,
  'claimDailyReward' : ActorMethod<
    [],
    { 'message' : string, 'success' : boolean, 'amount' : number }
  >,
  'depositFiat' : ActorMethod<[string, number], undefined>,
  /**
   * / Get the current user's profile
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Exchange Rate Management
   */
  'getExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'getOkpBalance' : ActorMethod<[], number>,
  'getOkpToCdfRate' : ActorMethod<[], number>,
  'getPortfolioValue' : ActorMethod<[], PortfolioValue>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStakes' : ActorMethod<[], Array<StakeRecord>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  /**
   * / Get a specific user's profile (must be owner or admin)
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Wallet Management
   */
  'getWallet' : ActorMethod<[], WalletBalance>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payMerchantOkp' : ActorMethod<
    [Principal, number, boolean],
    TransactionResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellCrypto' : ActorMethod<[SellCryptoRequest], TransactionResult>,
  'setExchangeRate' : ActorMethod<[SetExchangeRateRequest], undefined>,
  'setOkpToCdfRate' : ActorMethod<[number], undefined>,
  'stakeOkp' : ActorMethod<
    [number, bigint],
    { 'stakeId' : [] | [bigint], 'message' : string, 'success' : boolean }
  >,
  'transferOkp' : ActorMethod<[Principal, number], TransactionResult>,
  'unstakeOkp' : ActorMethod<[bigint], TransactionResult>,
  /**
   * / Profile Management
   */
  'updateProfile' : ActorMethod<[UpdateProfileRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];