/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuyCryptoRequest = IDL.Record({
  'paymentMethod' : IDL.Text,
  'asset' : IDL.Text,
  'fiatAmount' : IDL.Float64,
  'fiatCurrency' : IDL.Text,
});
export const WalletBalance = IDL.Record({
  'btc' : IDL.Float64,
  'cdf' : IDL.Float64,
  'eth' : IDL.Float64,
  'usd' : IDL.Float64,
  'usdt' : IDL.Float64,
});
export const TransactionResult = IDL.Record({
  'newBalance' : IDL.Opt(WalletBalance),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
});
export const ExchangeRate = IDL.Record({
  'pair' : IDL.Text,
  'buyRate' : IDL.Float64,
  'sellRate' : IDL.Float64,
});
export const PortfolioValue = IDL.Record({
  'totalCDF' : IDL.Float64,
  'totalUSD' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'asset' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fiatAmount' : IDL.Float64,
  'txType' : IDL.Text,
  'fiatCurrency' : IDL.Text,
  'cryptoAmount' : IDL.Float64,
});
export const SellCryptoRequest = IDL.Record({
  'asset' : IDL.Text,
  'fiatCurrency' : IDL.Text,
  'cryptoAmount' : IDL.Float64,
});
export const SetExchangeRateRequest = IDL.Record({
  'pair' : IDL.Text,
  'buyRate' : IDL.Float64,
  'sellRate' : IDL.Float64,
});
export const UpdateProfileRequest = IDL.Record({
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyCrypto' : IDL.Func([BuyCryptoRequest], [TransactionResult], []),
  'depositFiat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
  'getPortfolioValue' : IDL.Func([], [PortfolioValue], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [WalletBalance], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellCrypto' : IDL.Func([SellCryptoRequest], [TransactionResult], []),
  'setExchangeRate' : IDL.Func([SetExchangeRateRequest], [], []),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuyCryptoRequest = IDL.Record({
    'paymentMethod' : IDL.Text,
    'asset' : IDL.Text,
    'fiatAmount' : IDL.Float64,
    'fiatCurrency' : IDL.Text,
  });
  const WalletBalance = IDL.Record({
    'btc' : IDL.Float64,
    'cdf' : IDL.Float64,
    'eth' : IDL.Float64,
    'usd' : IDL.Float64,
    'usdt' : IDL.Float64,
  });
  const TransactionResult = IDL.Record({
    'newBalance' : IDL.Opt(WalletBalance),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
  });
  const ExchangeRate = IDL.Record({
    'pair' : IDL.Text,
    'buyRate' : IDL.Float64,
    'sellRate' : IDL.Float64,
  });
  const PortfolioValue = IDL.Record({
    'totalCDF' : IDL.Float64,
    'totalUSD' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'asset' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fiatAmount' : IDL.Float64,
    'txType' : IDL.Text,
    'fiatCurrency' : IDL.Text,
    'cryptoAmount' : IDL.Float64,
  });
  const SellCryptoRequest = IDL.Record({
    'asset' : IDL.Text,
    'fiatCurrency' : IDL.Text,
    'cryptoAmount' : IDL.Float64,
  });
  const SetExchangeRateRequest = IDL.Record({
    'pair' : IDL.Text,
    'buyRate' : IDL.Float64,
    'sellRate' : IDL.Float64,
  });
  const UpdateProfileRequest = IDL.Record({
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyCrypto' : IDL.Func([BuyCryptoRequest], [TransactionResult], []),
    'depositFiat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
    'getPortfolioValue' : IDL.Func([], [PortfolioValue], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [WalletBalance], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellCrypto' : IDL.Func([SellCryptoRequest], [TransactionResult], []),
    'setExchangeRate' : IDL.Func([SetExchangeRateRequest], [], []),
    'updateProfile' : IDL.Func([UpdateProfileRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };