/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KycRecord = IDL.Record({
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'reviewedAt' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuyCryptoRequest = IDL.Record({
  'paymentMethod' : IDL.Text,
  'asset' : IDL.Text,
  'fiatAmount' : IDL.Float64,
  'fiatCurrency' : IDL.Text,
});
export const WalletBalance = IDL.Record({
  'btc' : IDL.Float64,
  'cdf' : IDL.Float64,
  'eth' : IDL.Float64,
  'okp' : IDL.Float64,
  'usd' : IDL.Float64,
  'usdt' : IDL.Float64,
});
export const TransactionResult = IDL.Record({
  'newBalance' : IDL.Opt(WalletBalance),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const OkpAllocation = IDL.Record({
  'name' : IDL.Text,
  'locked' : IDL.Bool,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
  'percentage' : IDL.Float64,
});
export const OkpAdminStats = IDL.Record({
  'circulatingSupply' : IDL.Float64,
  'totalIssued' : IDL.Float64,
  'totalSupply' : IDL.Float64,
  'currentRate' : IDL.Float64,
  'totalBurned' : IDL.Float64,
  'allocations' : IDL.Vec(OkpAllocation),
  'totalStaked' : IDL.Float64,
  'rewardMultiplier' : IDL.Float64,
});
export const AdminStats = IDL.Record({
  'okpStats' : OkpAdminStats,
  'suspendedUsersCount' : IDL.Nat,
  'totalVolumeCdf' : IDL.Float64,
  'totalVolumeUsd' : IDL.Float64,
  'totalUsers' : IDL.Nat,
  'pendingKycCount' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
});
export const MobileMoneyRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'operator' : IDL.Text,
  'rejectionReason' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'amountCdf' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'asset' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fiatAmount' : IDL.Float64,
  'txType' : IDL.Text,
  'fiatCurrency' : IDL.Text,
  'cryptoAmount' : IDL.Float64,
});
export const UserProfileWithReferral = IDL.Record({
  'referralCode' : IDL.Text,
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'rewardClaimed' : IDL.Bool,
  'preferredCurrency' : IDL.Text,
  'referredAt' : IDL.Opt(IDL.Int),
  'referredBy' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
});
export const UserAdminView = IDL.Record({
  'principal' : IDL.Principal,
  'referral' : IDL.Opt(UserProfileWithReferral),
  'accountStatus' : IDL.Text,
  'role' : IDL.Text,
  'kycStatus' : IDL.Text,
  'walletBalance' : IDL.Opt(WalletBalance),
  'profile' : IDL.Opt(UserProfile),
});
export const ExchangeRate = IDL.Record({
  'pair' : IDL.Text,
  'buyRate' : IDL.Float64,
  'sellRate' : IDL.Float64,
});
export const PaymentConfig = IDL.Record({
  'tmbAccount' : IDL.Text,
  'equityBeneficiary' : IDL.Text,
  'equityAccount' : IDL.Text,
  'mpesaNumber' : IDL.Text,
  'rawbankAccount' : IDL.Text,
  'equitySwift' : IDL.Text,
  'airtelNumber' : IDL.Text,
});
export const PortfolioValue = IDL.Record({
  'totalCDF' : IDL.Float64,
  'totalUSD' : IDL.Float64,
});
export const Referral = IDL.Record({
  'activated' : IDL.Bool,
  'referredUser' : IDL.Principal,
  'rewardAmount' : IDL.Float64,
  'activatedAt' : IDL.Int,
  'referredAt' : IDL.Int,
});
export const ReferralStats = IDL.Record({
  'activated' : IDL.Nat,
  'totalOkpEarned' : IDL.Float64,
  'totalReferred' : IDL.Nat,
  'referrals' : IDL.Vec(Referral),
});
export const StakeRecord = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'startTime' : IDL.Int,
  'userId' : IDL.Principal,
  'claimed' : IDL.Bool,
  'rewardRate' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const SellCryptoRequest = IDL.Record({
  'asset' : IDL.Text,
  'fiatCurrency' : IDL.Text,
  'cryptoAmount' : IDL.Float64,
});
export const SetExchangeRateRequest = IDL.Record({
  'pair' : IDL.Text,
  'buyRate' : IDL.Float64,
  'sellRate' : IDL.Float64,
});
export const UpdateProfileRequest = IDL.Record({
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [], []),
  'applyReferralCode' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'approveKyc' : IDL.Func([IDL.Principal], [KycRecord], []),
  'approveMobileMoneyRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyCrypto' : IDL.Func([BuyCryptoRequest], [TransactionResult], []),
  'claimDailyReward' : IDL.Func(
      [],
      [
        IDL.Record({
          'message' : IDL.Text,
          'success' : IDL.Bool,
          'amount' : IDL.Float64,
        }),
      ],
      [],
    ),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'depositFiat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getActivatedListQuery' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllKyc' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
  'getAllMobileMoneyRequests' : IDL.Func(
      [],
      [IDL.Vec(MobileMoneyRequest)],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfileWithReferral))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserAdminView)], ['query']),
  'getAllWallets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WalletBalance))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfileWithReferral)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
  'getMyKyc' : IDL.Func([], [KycRecord], ['query']),
  'getMyMobileMoneyRequests' : IDL.Func(
      [],
      [IDL.Vec(MobileMoneyRequest)],
      ['query'],
    ),
  'getOkpAdminStats' : IDL.Func([], [OkpAdminStats], ['query']),
  'getOkpBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getOkpToCdfRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
  'getPortfolioValue' : IDL.Func([], [PortfolioValue], ['query']),
  'getReferralCodeQuery' : IDL.Func([], [IDL.Text], ['query']),
  'getReferralRewardsQuery' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferralStatsQuery' : IDL.Func([], [ReferralStats], ['query']),
  'getReferredListQuery' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getRewardMultiplier' : IDL.Func([], [IDL.Float64], ['query']),
  'getStakes' : IDL.Func([], [IDL.Vec(StakeRecord)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserPortfolio' : IDL.Func([IDL.Principal], [PortfolioValue], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileWithReferral)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [WalletBalance], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'payMerchantOkp' : IDL.Func(
      [IDL.Principal, IDL.Float64, IDL.Bool],
      [TransactionResult],
      [],
    ),
  'rejectKyc' : IDL.Func([IDL.Principal], [KycRecord], []),
  'rejectMobileMoneyRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resetPriceAdjustment' : IDL.Func([], [], []),
  'resetRewardMultiplier' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileWithReferral], [], []),
  'sellCrypto' : IDL.Func([SellCryptoRequest], [TransactionResult], []),
  'setExchangeRate' : IDL.Func([SetExchangeRateRequest], [], []),
  'setOkpToCdfRate' : IDL.Func([IDL.Float64], [], []),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'setRewardMultiplier' : IDL.Func([IDL.Float64], [], []),
  'stakeOkp' : IDL.Func(
      [IDL.Float64, IDL.Nat],
      [
        IDL.Record({
          'stakeId' : IDL.Opt(IDL.Nat),
          'message' : IDL.Text,
          'success' : IDL.Bool,
        }),
      ],
      [],
    ),
  'submitKyc' : IDL.Func([IDL.Text, IDL.Text], [KycRecord], []),
  'submitMobileMoneyDeposit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'submitMobileMoneyWithdrawal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'transferOkp' : IDL.Func(
      [IDL.Principal, IDL.Float64],
      [TransactionResult],
      [],
    ),
  'unstakeOkp' : IDL.Func([IDL.Nat], [TransactionResult], []),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KycRecord = IDL.Record({
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'reviewedAt' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuyCryptoRequest = IDL.Record({
    'paymentMethod' : IDL.Text,
    'asset' : IDL.Text,
    'fiatAmount' : IDL.Float64,
    'fiatCurrency' : IDL.Text,
  });
  const WalletBalance = IDL.Record({
    'btc' : IDL.Float64,
    'cdf' : IDL.Float64,
    'eth' : IDL.Float64,
    'okp' : IDL.Float64,
    'usd' : IDL.Float64,
    'usdt' : IDL.Float64,
  });
  const TransactionResult = IDL.Record({
    'newBalance' : IDL.Opt(WalletBalance),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const OkpAllocation = IDL.Record({
    'name' : IDL.Text,
    'locked' : IDL.Bool,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
    'percentage' : IDL.Float64,
  });
  const OkpAdminStats = IDL.Record({
    'circulatingSupply' : IDL.Float64,
    'totalIssued' : IDL.Float64,
    'totalSupply' : IDL.Float64,
    'currentRate' : IDL.Float64,
    'totalBurned' : IDL.Float64,
    'allocations' : IDL.Vec(OkpAllocation),
    'totalStaked' : IDL.Float64,
    'rewardMultiplier' : IDL.Float64,
  });
  const AdminStats = IDL.Record({
    'okpStats' : OkpAdminStats,
    'suspendedUsersCount' : IDL.Nat,
    'totalVolumeCdf' : IDL.Float64,
    'totalVolumeUsd' : IDL.Float64,
    'totalUsers' : IDL.Nat,
    'pendingKycCount' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
  });
  const MobileMoneyRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'operator' : IDL.Text,
    'rejectionReason' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'amountCdf' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'asset' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fiatAmount' : IDL.Float64,
    'txType' : IDL.Text,
    'fiatCurrency' : IDL.Text,
    'cryptoAmount' : IDL.Float64,
  });
  const UserProfileWithReferral = IDL.Record({
    'referralCode' : IDL.Text,
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'rewardClaimed' : IDL.Bool,
    'preferredCurrency' : IDL.Text,
    'referredAt' : IDL.Opt(IDL.Int),
    'referredBy' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
  });
  const UserAdminView = IDL.Record({
    'principal' : IDL.Principal,
    'referral' : IDL.Opt(UserProfileWithReferral),
    'accountStatus' : IDL.Text,
    'role' : IDL.Text,
    'kycStatus' : IDL.Text,
    'walletBalance' : IDL.Opt(WalletBalance),
    'profile' : IDL.Opt(UserProfile),
  });
  const ExchangeRate = IDL.Record({
    'pair' : IDL.Text,
    'buyRate' : IDL.Float64,
    'sellRate' : IDL.Float64,
  });
  const PaymentConfig = IDL.Record({
    'tmbAccount' : IDL.Text,
    'equityBeneficiary' : IDL.Text,
    'equityAccount' : IDL.Text,
    'mpesaNumber' : IDL.Text,
    'rawbankAccount' : IDL.Text,
    'equitySwift' : IDL.Text,
    'airtelNumber' : IDL.Text,
  });
  const PortfolioValue = IDL.Record({
    'totalCDF' : IDL.Float64,
    'totalUSD' : IDL.Float64,
  });
  const Referral = IDL.Record({
    'activated' : IDL.Bool,
    'referredUser' : IDL.Principal,
    'rewardAmount' : IDL.Float64,
    'activatedAt' : IDL.Int,
    'referredAt' : IDL.Int,
  });
  const ReferralStats = IDL.Record({
    'activated' : IDL.Nat,
    'totalOkpEarned' : IDL.Float64,
    'totalReferred' : IDL.Nat,
    'referrals' : IDL.Vec(Referral),
  });
  const StakeRecord = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'startTime' : IDL.Int,
    'userId' : IDL.Principal,
    'claimed' : IDL.Bool,
    'rewardRate' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const SellCryptoRequest = IDL.Record({
    'asset' : IDL.Text,
    'fiatCurrency' : IDL.Text,
    'cryptoAmount' : IDL.Float64,
  });
  const SetExchangeRateRequest = IDL.Record({
    'pair' : IDL.Text,
    'buyRate' : IDL.Float64,
    'sellRate' : IDL.Float64,
  });
  const UpdateProfileRequest = IDL.Record({
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [], []),
    'applyReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'approveKyc' : IDL.Func([IDL.Principal], [KycRecord], []),
    'approveMobileMoneyRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyCrypto' : IDL.Func([BuyCryptoRequest], [TransactionResult], []),
    'claimDailyReward' : IDL.Func(
        [],
        [
          IDL.Record({
            'message' : IDL.Text,
            'success' : IDL.Bool,
            'amount' : IDL.Float64,
          }),
        ],
        [],
      ),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'depositFiat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getActivatedListQuery' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllKyc' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
    'getAllMobileMoneyRequests' : IDL.Func(
        [],
        [IDL.Vec(MobileMoneyRequest)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfileWithReferral))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserAdminView)], ['query']),
    'getAllWallets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WalletBalance))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileWithReferral)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
    'getMyKyc' : IDL.Func([], [KycRecord], ['query']),
    'getMyMobileMoneyRequests' : IDL.Func(
        [],
        [IDL.Vec(MobileMoneyRequest)],
        ['query'],
      ),
    'getOkpAdminStats' : IDL.Func([], [OkpAdminStats], ['query']),
    'getOkpBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getOkpToCdfRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
    'getPortfolioValue' : IDL.Func([], [PortfolioValue], ['query']),
    'getReferralCodeQuery' : IDL.Func([], [IDL.Text], ['query']),
    'getReferralRewardsQuery' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferralStatsQuery' : IDL.Func([], [ReferralStats], ['query']),
    'getReferredListQuery' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getRewardMultiplier' : IDL.Func([], [IDL.Float64], ['query']),
    'getStakes' : IDL.Func([], [IDL.Vec(StakeRecord)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserPortfolio' : IDL.Func([IDL.Principal], [PortfolioValue], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileWithReferral)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [WalletBalance], ['query']),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'payMerchantOkp' : IDL.Func(
        [IDL.Principal, IDL.Float64, IDL.Bool],
        [TransactionResult],
        [],
      ),
    'rejectKyc' : IDL.Func([IDL.Principal], [KycRecord], []),
    'rejectMobileMoneyRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resetPriceAdjustment' : IDL.Func([], [], []),
    'resetRewardMultiplier' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileWithReferral], [], []),
    'sellCrypto' : IDL.Func([SellCryptoRequest], [TransactionResult], []),
    'setExchangeRate' : IDL.Func([SetExchangeRateRequest], [], []),
    'setOkpToCdfRate' : IDL.Func([IDL.Float64], [], []),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'setRewardMultiplier' : IDL.Func([IDL.Float64], [], []),
    'stakeOkp' : IDL.Func(
        [IDL.Float64, IDL.Nat],
        [
          IDL.Record({
            'stakeId' : IDL.Opt(IDL.Nat),
            'message' : IDL.Text,
            'success' : IDL.Bool,
          }),
        ],
        [],
      ),
    'submitKyc' : IDL.Func([IDL.Text, IDL.Text], [KycRecord], []),
    'submitMobileMoneyDeposit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'submitMobileMoneyWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'transferOkp' : IDL.Func(
        [IDL.Principal, IDL.Float64],
        [TransactionResult],
        [],
      ),
    'unstakeOkp' : IDL.Func([IDL.Nat], [TransactionResult], []),
    'updateProfile' : IDL.Func([UpdateProfileRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };