/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuyCryptoRequest {
  'paymentMethod' : string,
  'asset' : string,
  'fiatAmount' : number,
  'fiatCurrency' : string,
}
export interface ExchangeRate {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface PortfolioValue { 'totalCDF' : number, 'totalUSD' : number }
export interface SellCryptoRequest {
  'asset' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface SetExchangeRateRequest {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'asset' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'fiatAmount' : number,
  'txType' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface TransactionResult {
  'newBalance' : [] | [WalletBalance],
  'message' : string,
  'success' : boolean,
}
export interface UpdateProfileRequest {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export interface UserProfile {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletBalance {
  'btc' : number,
  'cdf' : number,
  'eth' : number,
  'usd' : number,
  'usdt' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyCrypto' : ActorMethod<[BuyCryptoRequest], TransactionResult>,
  'depositFiat' : ActorMethod<[string, number], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'getPortfolioValue' : ActorMethod<[], PortfolioValue>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[], WalletBalance>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellCrypto' : ActorMethod<[SellCryptoRequest], TransactionResult>,
  'setExchangeRate' : ActorMethod<[SetExchangeRateRequest], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];