/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'okpStats' : OkpAdminStats,
  'suspendedUsersCount' : bigint,
  'totalVolumeCdf' : number,
  'totalVolumeUsd' : number,
  'totalUsers' : bigint,
  'pendingKycCount' : bigint,
  'totalTransactions' : bigint,
}
export interface BuyCryptoRequest {
  'paymentMethod' : string,
  'asset' : string,
  'fiatAmount' : number,
  'fiatCurrency' : string,
}
export interface ExchangeRate {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface KycRecord {
  'status' : string,
  'userId' : Principal,
  'fullName' : string,
  'submittedAt' : bigint,
  'reviewedAt' : bigint,
  'phone' : string,
  'idDocumentBase64' : string,
  'selfieBase64' : string,
}
export interface MobileMoneyRequest {
  'id' : bigint,
  'status' : string,
  'userId' : Principal,
  'operator' : string,
  'rejectionReason' : string,
  'timestamp' : bigint,
  'txType' : string,
  'amountCdf' : number,
  'phone' : string,
}
export interface OkpAdminStats {
  'circulatingSupply' : number,
  'totalIssued' : number,
  'totalSupply' : number,
  'currentRate' : number,
  'totalBurned' : number,
  'allocations' : Array<OkpAllocation>,
  'totalStaked' : number,
  'rewardMultiplier' : number,
}
export interface OkpAllocation {
  'name' : string,
  'locked' : boolean,
  'description' : string,
  'amount' : number,
  'percentage' : number,
}
export interface PaymentConfig {
  'tmbAccount' : string,
  'equityBeneficiary' : string,
  'equityAccount' : string,
  'mpesaNumber' : string,
  'rawbankAccount' : string,
  'equitySwift' : string,
  'airtelNumber' : string,
}
export interface PortfolioValue { 'totalCDF' : number, 'totalUSD' : number }
export interface Referral {
  'activated' : boolean,
  'referredUser' : Principal,
  'rewardAmount' : number,
  'activatedAt' : bigint,
  'referredAt' : bigint,
}
export interface ReferralStats {
  'activated' : bigint,
  'totalOkpEarned' : number,
  'totalReferred' : bigint,
  'referrals' : Array<Referral>,
}
export interface SellCryptoRequest {
  'asset' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface SetExchangeRateRequest {
  'pair' : string,
  'buyRate' : number,
  'sellRate' : number,
}
export interface StakeRecord {
  'id' : bigint,
  'durationDays' : bigint,
  'startTime' : bigint,
  'userId' : Principal,
  'claimed' : boolean,
  'rewardRate' : number,
  'amount' : number,
}
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'asset' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'fiatAmount' : number,
  'txType' : string,
  'fiatCurrency' : string,
  'cryptoAmount' : number,
}
export interface TransactionResult {
  'newBalance' : [] | [WalletBalance],
  'message' : string,
  'success' : boolean,
}
export interface UpdateProfileRequest {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export interface UserAdminView {
  'principal' : Principal,
  'referral' : [] | [UserProfileWithReferral],
  'accountStatus' : string,
  'role' : string,
  'kycStatus' : string,
  'walletBalance' : [] | [WalletBalance],
  'profile' : [] | [UserProfile],
}
export interface UserProfile {
  'country' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export interface UserProfileWithReferral {
  'referralCode' : string,
  'country' : string,
  'displayName' : string,
  'rewardClaimed' : boolean,
  'preferredCurrency' : string,
  'referredAt' : [] | [bigint],
  'referredBy' : [] | [Principal],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletBalance {
  'btc' : number,
  'cdf' : number,
  'eth' : number,
  'okp' : number,
  'usd' : number,
  'usdt' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateUser' : ActorMethod<[Principal], undefined>,
  'applyReferralCode' : ActorMethod<
    [string],
    { 'message' : string, 'success' : boolean }
  >,
  'approveKyc' : ActorMethod<[Principal], KycRecord>,
  'approveMobileMoneyRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyCrypto' : ActorMethod<[BuyCryptoRequest], TransactionResult>,
  'claimDailyReward' : ActorMethod<
    [],
    { 'message' : string, 'success' : boolean, 'amount' : number }
  >,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'depositFiat' : ActorMethod<[string, number], undefined>,
  'getActivatedListQuery' : ActorMethod<[], Array<Principal>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllKyc' : ActorMethod<[], Array<KycRecord>>,
  'getAllMobileMoneyRequests' : ActorMethod<[], Array<MobileMoneyRequest>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUserProfiles' : ActorMethod<
    [],
    Array<[Principal, UserProfileWithReferral]>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserAdminView>>,
  'getAllWallets' : ActorMethod<[], Array<[Principal, WalletBalance]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileWithReferral]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'getMyKyc' : ActorMethod<[], KycRecord>,
  'getMyMobileMoneyRequests' : ActorMethod<[], Array<MobileMoneyRequest>>,
  'getOkpAdminStats' : ActorMethod<[], OkpAdminStats>,
  'getOkpBalance' : ActorMethod<[], number>,
  'getOkpToCdfRate' : ActorMethod<[], number>,
  'getPaymentConfig' : ActorMethod<[], PaymentConfig>,
  'getPortfolioValue' : ActorMethod<[], PortfolioValue>,
  'getReferralCodeQuery' : ActorMethod<[], string>,
  'getReferralRewardsQuery' : ActorMethod<[], bigint>,
  'getReferralStatsQuery' : ActorMethod<[], ReferralStats>,
  'getReferredListQuery' : ActorMethod<[], Array<Principal>>,
  'getRewardMultiplier' : ActorMethod<[], number>,
  'getStakes' : ActorMethod<[], Array<StakeRecord>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserPortfolio' : ActorMethod<[Principal], PortfolioValue>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileWithReferral]>,
  'getWallet' : ActorMethod<[], WalletBalance>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payMerchantOkp' : ActorMethod<
    [Principal, number, boolean],
    TransactionResult
  >,
  'rejectKyc' : ActorMethod<[Principal], KycRecord>,
  'rejectMobileMoneyRequest' : ActorMethod<[bigint, string], undefined>,
  'resetPriceAdjustment' : ActorMethod<[], undefined>,
  'resetRewardMultiplier' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileWithReferral], undefined>,
  'sellCrypto' : ActorMethod<[SellCryptoRequest], TransactionResult>,
  'setExchangeRate' : ActorMethod<[SetExchangeRateRequest], undefined>,
  'setOkpToCdfRate' : ActorMethod<[number], undefined>,
  'setPaymentConfig' : ActorMethod<[PaymentConfig], undefined>,
  'setRewardMultiplier' : ActorMethod<[number], undefined>,
  'stakeOkp' : ActorMethod<
    [number, bigint],
    { 'stakeId' : [] | [bigint], 'message' : string, 'success' : boolean }
  >,
  'submitKyc' : ActorMethod<[string, string, string, string], KycRecord>,
  'submitMobileMoneyDeposit' : ActorMethod<[string, string, number], bigint>,
  'submitMobileMoneyWithdrawal' : ActorMethod<[string, string, number], bigint>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'transferOkp' : ActorMethod<[Principal, number], TransactionResult>,
  'unstakeOkp' : ActorMethod<[bigint], TransactionResult>,
  /**
   * / Profile Management
   */
  'updateProfile' : ActorMethod<[UpdateProfileRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];