/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaymentConfig {
    tmbAccount: string;
    equityBeneficiary: string;
    equityAccount: string;
    mpesaNumber: string;
    rawbankAccount: string;
    equitySwift: string;
    airtelNumber: string;
}
export interface UserAdminView {
    principal: Principal;
    referral?: UserProfileWithReferral;
    accountStatus: string;
    role: string;
    kycStatus: string;
    walletBalance?: WalletBalance;
    profile?: UserProfile;
}
export interface TransactionResult {
    newBalance?: WalletBalance;
    message: string;
    success: boolean;
}
export interface WalletBalance {
    btc: number;
    cdf: number;
    eth: number;
    okp: number;
    usd: number;
    usdt: number;
}
export interface OkpAdminStats {
    circulatingSupply: number;
    totalIssued: number;
    totalSupply: number;
    currentRate: number;
    totalBurned: number;
    allocations: Array<OkpAllocation>;
    totalStaked: number;
    rewardMultiplier: number;
}
export interface ExchangeRate {
    pair: string;
    buyRate: number;
    sellRate: number;
}
export interface OkpAllocation {
    name: string;
    locked: boolean;
    description: string;
    amount: number;
    percentage: number;
}
export interface ReferralStats {
    activated: bigint;
    totalOkpEarned: number;
    totalReferred: bigint;
    referrals: Array<Referral>;
}
export interface BuyCryptoRequest {
    paymentMethod: string;
    asset: string;
    fiatAmount: number;
    fiatCurrency: string;
}
export interface StakeRecord {
    id: bigint;
    durationDays: bigint;
    startTime: bigint;
    userId: Principal;
    claimed: boolean;
    rewardRate: number;
    amount: number;
}
export interface UserProfileWithReferral {
    referralCode: string;
    country: string;
    displayName: string;
    rewardClaimed: boolean;
    preferredCurrency: string;
    referredAt?: bigint;
    referredBy?: Principal;
}
export interface Transaction {
    id: bigint;
    status: string;
    paymentMethod: string;
    asset: string;
    userId: Principal;
    timestamp: bigint;
    fiatAmount: number;
    txType: string;
    fiatCurrency: string;
    cryptoAmount: number;
}
export interface SetExchangeRateRequest {
    pair: string;
    buyRate: number;
    sellRate: number;
}
export interface UpdateProfileRequest {
    country: string;
    displayName: string;
    preferredCurrency: string;
}
export interface MobileMoneyRequest {
    id: bigint;
    status: string;
    userId: Principal;
    operator: string;
    rejectionReason: string;
    timestamp: bigint;
    txType: string;
    amountCdf: number;
    phone: string;
}
export interface KycRecord {
    status: string;
    userId: Principal;
    fullName: string;
    submittedAt: bigint;
    reviewedAt: bigint;
    phone: string;
}
export interface AdminStats {
    okpStats: OkpAdminStats;
    suspendedUsersCount: bigint;
    totalVolumeCdf: number;
    totalVolumeUsd: number;
    totalUsers: bigint;
    pendingKycCount: bigint;
    totalTransactions: bigint;
}
export interface Referral {
    activated: boolean;
    referredUser: Principal;
    rewardAmount: number;
    activatedAt: bigint;
    referredAt: bigint;
}
export interface SellCryptoRequest {
    asset: string;
    fiatCurrency: string;
    cryptoAmount: number;
}
export interface UserProfile {
    country: string;
    displayName: string;
    preferredCurrency: string;
}
export interface PortfolioValue {
    totalCDF: number;
    totalUSD: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateUser(user: Principal): Promise<void>;
    applyReferralCode(code: string): Promise<{
        message: string;
        success: boolean;
    }>;
    approveKyc(user: Principal): Promise<KycRecord>;
    approveMobileMoneyRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    buyCrypto(request: BuyCryptoRequest): Promise<TransactionResult>;
    claimDailyReward(): Promise<{
        message: string;
        success: boolean;
        amount: number;
    }>;
    claimFirstAdmin(): Promise<void>;
    depositFiat(currency: string, amount: number): Promise<void>;
    getActivatedListQuery(): Promise<Array<Principal>>;
    getAdminStats(): Promise<AdminStats>;
    getAllKyc(): Promise<Array<KycRecord>>;
    getAllMobileMoneyRequests(): Promise<Array<MobileMoneyRequest>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfileWithReferral]>>;
    getAllUsers(): Promise<Array<UserAdminView>>;
    getAllWallets(): Promise<Array<[Principal, WalletBalance]>>;
    getCallerUserProfile(): Promise<UserProfileWithReferral | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExchangeRates(): Promise<Array<ExchangeRate>>;
    getMyKyc(): Promise<KycRecord>;
    getMyMobileMoneyRequests(): Promise<Array<MobileMoneyRequest>>;
    getOkpAdminStats(): Promise<OkpAdminStats>;
    getOkpBalance(): Promise<number>;
    getOkpToCdfRate(): Promise<number>;
    getPaymentConfig(): Promise<PaymentConfig>;
    getPortfolioValue(): Promise<PortfolioValue>;
    getReferralCodeQuery(): Promise<string>;
    getReferralRewardsQuery(): Promise<bigint>;
    getReferralStatsQuery(): Promise<ReferralStats>;
    getReferredListQuery(): Promise<Array<Principal>>;
    getRewardMultiplier(): Promise<number>;
    getStakes(): Promise<Array<StakeRecord>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserPortfolio(user: Principal): Promise<PortfolioValue>;
    getUserProfile(user: Principal): Promise<UserProfileWithReferral | null>;
    getWallet(): Promise<WalletBalance>;
    isAdminAssigned(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    payMerchantOkp(merchant: Principal, okpAmount: number, convertToCdf: boolean): Promise<TransactionResult>;
    rejectKyc(user: Principal): Promise<KycRecord>;
    rejectMobileMoneyRequest(requestId: bigint, reason: string): Promise<void>;
    resetPriceAdjustment(): Promise<void>;
    resetRewardMultiplier(): Promise<void>;
    saveCallerUserProfile(profile: UserProfileWithReferral): Promise<void>;
    sellCrypto(request: SellCryptoRequest): Promise<TransactionResult>;
    setExchangeRate(request: SetExchangeRateRequest): Promise<void>;
    setOkpToCdfRate(rate: number): Promise<void>;
    setPaymentConfig(config: PaymentConfig): Promise<void>;
    setRewardMultiplier(multiplier: number): Promise<void>;
    stakeOkp(amount: number, durationDays: bigint): Promise<{
        stakeId?: bigint;
        message: string;
        success: boolean;
    }>;
    submitKyc(fullName: string, phone: string): Promise<KycRecord>;
    submitMobileMoneyDeposit(phone: string, operator: string, amountCdf: number): Promise<bigint>;
    submitMobileMoneyWithdrawal(phone: string, operator: string, amountCdf: number): Promise<bigint>;
    suspendUser(user: Principal): Promise<void>;
    transferOkp(to: Principal, amount: number): Promise<TransactionResult>;
    unstakeOkp(stakeId: bigint): Promise<TransactionResult>;
    /**
     * / Profile Management
     */
    updateProfile(request: UpdateProfileRequest): Promise<void>;
}
import type { TransactionResult as _TransactionResult, UserAdminView as _UserAdminView, UserProfile as _UserProfile, UserProfileWithReferral as _UserProfileWithReferral, UserRole as _UserRole, WalletBalance as _WalletBalance } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return result;
        }
    }
    async applyReferralCode(arg0: string): Promise<{
        message: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferralCode(arg0);
            return result;
        }
    }
    async approveKyc(arg0: Principal): Promise<KycRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.approveKyc(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveKyc(arg0);
            return result;
        }
    }
    async approveMobileMoneyRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMobileMoneyRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMobileMoneyRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async buyCrypto(arg0: BuyCryptoRequest): Promise<TransactionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.buyCrypto(arg0);
                return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyCrypto(arg0);
            return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimDailyReward(): Promise<{
        message: string;
        success: boolean;
        amount: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyReward();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyReward();
            return result;
        }
    }
    async claimFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdmin();
            return result;
        }
    }
    async depositFiat(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositFiat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositFiat(arg0, arg1);
            return result;
        }
    }
    async getActivatedListQuery(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivatedListQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivatedListQuery();
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllKyc(): Promise<Array<KycRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKyc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKyc();
            return result;
        }
    }
    async getAllMobileMoneyRequests(): Promise<Array<MobileMoneyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMobileMoneyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMobileMoneyRequests();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfileWithReferral]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserAdminView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWallets(): Promise<Array<[Principal, WalletBalance]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWallets();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileWithReferral | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeRates(): Promise<Array<ExchangeRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRates();
            return result;
        }
    }
    async getMyKyc(): Promise<KycRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKyc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKyc();
            return result;
        }
    }
    async getMyMobileMoneyRequests(): Promise<Array<MobileMoneyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMobileMoneyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMobileMoneyRequests();
            return result;
        }
    }
    async getOkpAdminStats(): Promise<OkpAdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getOkpAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOkpAdminStats();
            return result;
        }
    }
    async getOkpBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getOkpBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOkpBalance();
            return result;
        }
    }
    async getOkpToCdfRate(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getOkpToCdfRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOkpToCdfRate();
            return result;
        }
    }
    async getPaymentConfig(): Promise<PaymentConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentConfig();
            return result;
        }
    }
    async getPortfolioValue(): Promise<PortfolioValue> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioValue();
            return result;
        }
    }
    async getReferralCodeQuery(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCodeQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCodeQuery();
            return result;
        }
    }
    async getReferralRewardsQuery(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralRewardsQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralRewardsQuery();
            return result;
        }
    }
    async getReferralStatsQuery(): Promise<ReferralStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralStatsQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralStatsQuery();
            return result;
        }
    }
    async getReferredListQuery(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferredListQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferredListQuery();
            return result;
        }
    }
    async getRewardMultiplier(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardMultiplier();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardMultiplier();
            return result;
        }
    }
    async getStakes(): Promise<Array<StakeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStakes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStakes();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return result;
        }
    }
    async getUserPortfolio(arg0: Principal): Promise<PortfolioValue> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPortfolio(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileWithReferral | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<WalletBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return result;
        }
    }
    async isAdminAssigned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminAssigned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminAssigned();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async payMerchantOkp(arg0: Principal, arg1: number, arg2: boolean): Promise<TransactionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.payMerchantOkp(arg0, arg1, arg2);
                return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payMerchantOkp(arg0, arg1, arg2);
            return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectKyc(arg0: Principal): Promise<KycRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectKyc(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectKyc(arg0);
            return result;
        }
    }
    async rejectMobileMoneyRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMobileMoneyRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMobileMoneyRequest(arg0, arg1);
            return result;
        }
    }
    async resetPriceAdjustment(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPriceAdjustment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPriceAdjustment();
            return result;
        }
    }
    async resetRewardMultiplier(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetRewardMultiplier();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetRewardMultiplier();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileWithReferral): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileWithReferral_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileWithReferral_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sellCrypto(arg0: SellCryptoRequest): Promise<TransactionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sellCrypto(arg0);
                return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sellCrypto(arg0);
            return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setExchangeRate(arg0: SetExchangeRateRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExchangeRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExchangeRate(arg0);
            return result;
        }
    }
    async setOkpToCdfRate(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOkpToCdfRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOkpToCdfRate(arg0);
            return result;
        }
    }
    async setPaymentConfig(arg0: PaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentConfig(arg0);
            return result;
        }
    }
    async setRewardMultiplier(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRewardMultiplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRewardMultiplier(arg0);
            return result;
        }
    }
    async stakeOkp(arg0: number, arg1: bigint): Promise<{
        stakeId?: bigint;
        message: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.stakeOkp(arg0, arg1);
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stakeOkp(arg0, arg1);
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitKyc(arg0: string, arg1: string): Promise<KycRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKyc(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKyc(arg0, arg1);
            return result;
        }
    }
    async submitMobileMoneyDeposit(arg0: string, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMobileMoneyDeposit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMobileMoneyDeposit(arg0, arg1, arg2);
            return result;
        }
    }
    async submitMobileMoneyWithdrawal(arg0: string, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMobileMoneyWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMobileMoneyWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async suspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async transferOkp(arg0: Principal, arg1: number): Promise<TransactionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferOkp(arg0, arg1);
                return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferOkp(arg0, arg1);
            return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unstakeOkp(arg0: bigint): Promise<TransactionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unstakeOkp(arg0);
                return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unstakeOkp(arg0);
            return from_candid_TransactionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_TransactionResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionResult): TransactionResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserAdminView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAdminView): UserAdminView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileWithReferral_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileWithReferral): UserProfileWithReferral {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileWithReferral]): UserProfileWithReferral | null {
    return value.length === 0 ? null : from_candid_UserProfileWithReferral_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletBalance]): WalletBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    referral: [] | [_UserProfileWithReferral];
    accountStatus: string;
    role: string;
    kycStatus: string;
    walletBalance: [] | [_WalletBalance];
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    referral?: UserProfileWithReferral;
    accountStatus: string;
    role: string;
    kycStatus: string;
    walletBalance?: WalletBalance;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        referral: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.referral)),
        accountStatus: value.accountStatus,
        role: value.role,
        kycStatus: value.kycStatus,
        walletBalance: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.walletBalance)),
        profile: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stakeId: [] | [bigint];
    message: string;
    success: boolean;
}): {
    stakeId?: bigint;
    message: string;
    success: boolean;
} {
    return {
        stakeId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.stakeId)),
        message: value.message,
        success: value.success
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newBalance: [] | [_WalletBalance];
    message: string;
    success: boolean;
}): {
    newBalance?: WalletBalance;
    message: string;
    success: boolean;
} {
    return {
        newBalance: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.newBalance)),
        message: value.message,
        success: value.success
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    country: string;
    displayName: string;
    rewardClaimed: boolean;
    preferredCurrency: string;
    referredAt: [] | [bigint];
    referredBy: [] | [Principal];
}): {
    referralCode: string;
    country: string;
    displayName: string;
    rewardClaimed: boolean;
    preferredCurrency: string;
    referredAt?: bigint;
    referredBy?: Principal;
} {
    return {
        referralCode: value.referralCode,
        country: value.country,
        displayName: value.displayName,
        rewardClaimed: value.rewardClaimed,
        preferredCurrency: value.preferredCurrency,
        referredAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.referredAt)),
        referredBy: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.referredBy))
    };
}
function from_candid_tuple_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfileWithReferral]): [Principal, UserProfileWithReferral] {
    return [
        value[0],
        from_candid_UserProfileWithReferral_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAdminView>): Array<UserAdminView> {
    return value.map((x)=>from_candid_UserAdminView_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfileWithReferral]>): Array<[Principal, UserProfileWithReferral]> {
    return value.map((x)=>from_candid_tuple_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfileWithReferral_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileWithReferral): _UserProfileWithReferral {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    country: string;
    displayName: string;
    rewardClaimed: boolean;
    preferredCurrency: string;
    referredAt?: bigint;
    referredBy?: Principal;
}): {
    referralCode: string;
    country: string;
    displayName: string;
    rewardClaimed: boolean;
    preferredCurrency: string;
    referredAt: [] | [bigint];
    referredBy: [] | [Principal];
} {
    return {
        referralCode: value.referralCode,
        country: value.country,
        displayName: value.displayName,
        rewardClaimed: value.rewardClaimed,
        preferredCurrency: value.preferredCurrency,
        referredAt: value.referredAt ? candid_some(value.referredAt) : candid_none(),
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
